Update workflows

diff --git a/.github/workflows/extract-configs-proxy.yml b/.github/workflows/extract-configs-proxy.yml
--- a/.github/workflows/extract-configs-proxy.yml
+++ b/.github/workflows/extract-configs-proxy.yml
@@ -1,4 +1,4 @@
-name: "Extract proxy configs"
+name: "Extract Minecraft proxy configs"
 
 on:
    workflow_dispatch:
@@ -7,46 +7,46 @@ on:
             description: 'Proxy type'
             required: true
 jobs:
-  generate-minecraft-configs:
+  generate-proxy-configs:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout repository
-        uses: actions/checkout@v2
+        uses: actions/checkout@v4
   
       - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v1
+        uses: docker/setup-buildx-action@v3
   
-      - name: Pull itzg/bungeecord image
-        run: docker pull itzg/bungeecord
+      - name: Pull itzg/mc-proxy image
+        run: docker pull itzg/mc-proxy
   
-      - name: Start Minecraft Server
+      - name: Start Minecraft proxy
         run: |
             docker run -d \
             -e EULA=TRUE \
             -e TYPE=${{ github.event.inputs.proxy_type }} \
             -p 25565:25577 \
-            --name minecraft-server \
+            --name minecraft-proxy \
             itzg/bungeecord
-            
+
       - name: Wait for container to become healthy
         run: |
-              while [[ "$(docker inspect -f '{{.State.Health.Status}}' minecraft-server)" != "healthy" ]]; do
-                if [[ "$(docker inspect -f '{{.State.Status}}' minecraft-server)" == "exited" ]]; then
+              while [[ "$(docker inspect -f '{{.State.Health.Status}}' minecraft-proxy)" != "healthy" ]]; do
+                if [[ "$(docker inspect -f '{{.State.Status}}' minecraft-proxy)" == "exited" ]]; then
                   echo "Container has stopped. Aborting workflow."
                   exit 1
                 fi
                 sleep 5
               done
 
-      - name: Stop Minecraft Server
-        run: docker stop minecraft-server
+      - name: Stop Minecraft proxy
+        run: docker stop minecraft-proxy
 
       - name: Copy configuration files
         run: |
           mkdir -p ${{ github.event.inputs.proxy_type }}
-          docker cp -q minecraft-server:/server/velocity.toml ./${{ github.event.inputs.proxy_type }}/velocity.toml || echo "not found, skipping"
-          docker cp -q minecraft-server:/server/config.yml ./${{ github.event.inputs.proxy_type }}/config.yml || echo "not found, skipping"
-          docker cp -q minecraft-server:/server/waterfall.yml ./${{ github.event.inputs.proxy_type }}/waterfall.yml || echo "not found, skipping"
+          docker cp -q minecraft-proxy:/server/velocity.toml ./${{ github.event.inputs.proxy_type }}/velocity.toml || echo "not found, skipping"
+          docker cp -q minecraft-proxy:/server/config.yml ./${{ github.event.inputs.proxy_type }}/config.yml || echo "not found, skipping"
+          docker cp -q minecraft-proxy:/server/waterfall.yml ./${{ github.event.inputs.proxy_type }}/waterfall.yml || echo "not found, skipping"
 
       - name: Commit configuration files
         env:
@@ -55,8 +55,8 @@ jobs:
           git config user.name github-actions[bot]
           git config user.email github-actions[bot]@users.noreply.github.com
           git add ${{ github.event.inputs.proxy_type }}
-          git commit -m "Add configuration files for Proxy version ${{ github.event.inputs.proxy_type }}"
+          git commit -m "Add configuration files for Proxy type ${{ github.event.inputs.proxy_type }}"
           git push origin HEAD:${{ github.event.inputs.proxy_type }}
 
-      - name: Clear away Minecraft Server
-        run: docker rm minecraft-server
+      - name: Clear away Minecraft proxy
+        run: docker rm minecraft-proxy
